name: Building macOS x86

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps Installing
      run: brew install cmake gcc@11 ninja

    - name: Build
      run: |
        mkdir build 
        cd build
        cmake .. -G Ninja
        ninja
        ./cpptutorial
        