name: CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  buildubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Deps Installing
        run: |
          sudo apt-get update  
          sudo apt install -y cmake ninja-build 

      - name: Building
        run: |
          mkdir build
          cd build/
          cmake .. -G Ninja
          ninja
          ./cpptutorial
          
  buildmacos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Deps Installing
        run: |
          brew update
          brew install gcc@10 ninja cmake 

      - name: Building
        run: |
          mkdir build
          cd build/
          cmake .. -G Ninja
          ninja
          ./cpptutorial
